[package]
name = "homectl_macros"
version = "0.1.0"
authors = ["arprv <arprv@protonmail.com>"]
edition = "2018"

[dependencies]
syn = "0.15.39"
quote = "0.6.13"
proc-macro2 = "0.4.30"

[lib]
proc-macro = true
